# Generated by Django 3.2 on 2021-04-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills_info', models.CharField(default=False, max_length=50)),
                ('education', models.CharField(default=False, max_length=50)),
                ('select_experience', models.CharField(default=False, max_length=50)),
                ('select_emp_type', models.CharField(default=False, max_length=50)),
                ('membership', models.CharField(default=False, max_length=250)),
                ('name', models.CharField(default=False, max_length=50)),
                ('dob', models.CharField(default=False, max_length=50)),
                ('communication_address', models.CharField(default=False, max_length=250)),
                ('pincode', models.PositiveIntegerField(default=False)),
                ('phone_number1', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_employee',
            },
        ),
    ]
